# Generated by WeaveFFI 0.24.0 from lib.rs
# DO NOT EDIT. Your changes will be overwritten.
# To regenerate: weaveffi generate lib.rs -o <out>

from .gifmaker_core import *  # noqa: F401,F403

# END __init__.py
