# Generated by WeaveFFI 0.24.0 from lib.rs
# DO NOT EDIT. Your changes will be overwritten.
# To regenerate: weaveffi generate lib.rs -o <out>

import builtins
from abc import ABC, abstractmethod
from enum import IntEnum
from typing import Dict, Iterator, List, Optional, Type

class Error(Exception):
    GENERIC_ERROR_CODE: int
    PANIC_ERROR_CODE: int
    MARSHAL_ERROR_CODE: int
    FOREIGN_ERROR_CODE: int
    CANCELLED_ERROR_CODE: int
    code: int
    message: str
    def __init__(self, code: int, message: str) -> None: ...

class ConversionError(Error):
    InvalidOptions: Type["InvalidOptions"]
    InvalidInput: Type["InvalidInput"]
    EncoderUnavailable: Type["EncoderUnavailable"]
    EncodingFailed: Type["EncodingFailed"]
    TimedOut: Type["TimedOut"]
    OutputFailed: Type["OutputFailed"]
    UnsupportedMotion: Type["UnsupportedMotion"]
    def __init__(self, code: int, message: str) -> None: ...

# FPS must be 1–30 and width must be 100–800 pixels.
class InvalidOptions(ConversionError):
    CODE: int
    def __init__(self, message: str = ...) -> None: ...

# The input is missing, empty, or larger than 100 MiB.
class InvalidInput(ConversionError):
    CODE: int
    def __init__(self, message: str = ...) -> None: ...

# FFmpeg is unavailable.
class EncoderUnavailable(ConversionError):
    CODE: int
    def __init__(self, message: str = ...) -> None: ...

# The video could not be decoded or encoded.
class EncodingFailed(ConversionError):
    CODE: int
    def __init__(self, message: str = ...) -> None: ...

# Conversion exceeded the two minute limit.
class TimedOut(ConversionError):
    CODE: int
    def __init__(self, message: str = ...) -> None: ...

# The output could not be written.
class OutputFailed(ConversionError):
    CODE: int
    def __init__(self, message: str = ...) -> None: ...

# Use one supported whole-image motion instruction.
class UnsupportedMotion(ConversionError):
    CODE: int
    def __init__(self, message: str = ...) -> None: ...

# Convert a server-owned local video into a looping, palette-optimized GIF.
def convert(input: str, output: str, fps: int, width: int) -> int: ...

# Resolve a bounded instruction to a safe motion plan; never returns executable code.
def plan_motion(prompt: str) -> str: ...

# Encode a server-owned, consecutive lossless PNG sequence without resizing it.
def encode_motion(frames: str, output: str, fps: int, count: int) -> int: ...

# END gifmaker_core.pyi
