// Generated by WeaveFFI 0.24.0 from lib.rs
// DO NOT EDIT. Your changes will be overwritten.
// To regenerate: weaveffi generate lib.rs -o <out>

#ifndef GIFMAKER_CORE_H
#define GIFMAKER_CORE_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#ifndef GIFMAKER_CORE_API
#  if defined(_WIN32) || defined(__CYGWIN__)
#    ifdef GIFMAKER_CORE_BUILD
#      define GIFMAKER_CORE_API __declspec(dllexport)
#    else
#      define GIFMAKER_CORE_API __declspec(dllimport)
#    endif
#  elif defined(__EMSCRIPTEN__)
#    define GIFMAKER_CORE_API __attribute__((used, visibility("default")))
#  elif defined(__GNUC__) && (__GNUC__ >= 4)
#    define GIFMAKER_CORE_API __attribute__((visibility("default")))
#  else
#    define GIFMAKER_CORE_API
#  endif
#endif

#ifndef GIFMAKER_CORE_DEPRECATED
#  if defined(_MSC_VER)
#    define GIFMAKER_CORE_DEPRECATED(msg) __declspec(deprecated(msg))
#  elif defined(__GNUC__) || defined(__clang__)
#    define GIFMAKER_CORE_DEPRECATED(msg) __attribute__((deprecated(msg)))
#  else
#    define GIFMAKER_CORE_DEPRECATED(msg)
#  endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* The C ABI revision this header was generated against. The producer
   exports gifmaker_core_abi_version() so a consumer can refuse to load a
   library built for a different revision. */
#define GIFMAKER_CORE_ABI_VERSION 3u
GIFMAKER_CORE_API uint32_t gifmaker_core_abi_version(void);

/* Error slot written by every fallible call. `message` is NUL-terminated
   UTF-8. `payload_ptr`/`payload_len` hold the matched error code's fields
   serialized in the value buffer format (null when the code declares no
   fields). Both are released by gifmaker_core_error_clear. Positive codes are
   the API's declared error codes; negative codes are runtime traps:
   -1 generic, -2 producer panic, -3 marshalling failure, -4 a callback
   interface implementation failed, -5 cancelled. */
typedef struct gifmaker_core_error {
    int32_t code;
    const char* message;
    const uint8_t* payload_ptr;
    size_t payload_len;
} gifmaker_core_error;

/* Fill `err` with `code` and a producer-owned copy of `message`. Callback
   interface implementations call this to report a failure (code -4)
   without allocating with a foreign allocator. */
GIFMAKER_CORE_API void gifmaker_core_error_set(gifmaker_core_error* err, int32_t code, const char* message);
GIFMAKER_CORE_API void gifmaker_core_error_clear(gifmaker_core_error* err);

/* Async completions receive a heap-boxed error the consumer owns;
   gifmaker_core_error_free releases the message, the payload, and the box.
   NULL is a no-op. */
GIFMAKER_CORE_API void gifmaker_core_error_free(gifmaker_core_error* err);

/* Release a string, bytes, or value buffer the producer returned. */
GIFMAKER_CORE_API void gifmaker_core_free_bytes(uint8_t* ptr, size_t len);

/* Cancellation for `cancellable` async functions. A token starts with
   one reference owned by the consumer; the producer takes its own for
   each call it is passed to, so the consumer may cancel and destroy its
   reference at any time. A cancelled call completes with code -5. */
typedef struct gifmaker_core_cancel_token gifmaker_core_cancel_token;
GIFMAKER_CORE_API gifmaker_core_cancel_token* gifmaker_core_cancel_token_create(void);
GIFMAKER_CORE_API void gifmaker_core_cancel_token_cancel(gifmaker_core_cancel_token* token);
GIFMAKER_CORE_API bool gifmaker_core_cancel_token_is_cancelled(const gifmaker_core_cancel_token* token);
GIFMAKER_CORE_API void gifmaker_core_cancel_token_destroy(gifmaker_core_cancel_token* token);

/* Linear-memory allocator the Wasm glue stages arguments through.
   Exported by wasm32 producers only. */
GIFMAKER_CORE_API uint8_t* gifmaker_core_alloc(uint32_t size);
GIFMAKER_CORE_API void gifmaker_core_dealloc(uint8_t* ptr, uint32_t size);

/* Live-allocation counters for leak checks in tests: 0 objects,
   1 callbacks, 2 iterators, 3 cancel tokens, 4 returned allocations.
   Always 0 unless the producer enables the `leak-check` feature. */
GIFMAKER_CORE_API uint64_t gifmaker_core_debug_live(int32_t kind);

/* Contract checksums, one per top-level module. A consumer compares
   each function's result with the constant it was generated against
   before making any other call. */
#define GIFMAKER_CORE_GIF_CHECKSUM 0x8043e3cf4a8baf04ull
GIFMAKER_CORE_API uint64_t gifmaker_core_gif_checksum(void);

/*
 * Strings, bytes, and value buffers cross as (ptr, len) pairs. A
 * parameter named "v" expands to a view borrowed for the call:
 *   const uint8_t* v_ptr, size_t v_len
 * Strings are UTF-8 without a NUL terminator; NULL with length 0 is
 * the empty value. A returned string, bytes, or buffer is
 * `const uint8_t*` with a trailing `size_t* out_len`, owned by the
 * caller and released with gifmaker_core_free_bytes.
 * Records, rich enums, lists, maps, and optionals are serialized
 * in the little-endian value buffer format; when generated,
 * gifmaker_core_buffer.h declares a C struct and codec for each.
 */

/** Error codes reported by throwing functions in the `gif` module tree. */
typedef enum {
    /** FPS must be 1–30 and width must be 100–800 pixels. */
    gifmaker_core_gif_ConversionError_InvalidOptions = 1,
    /** The input is missing, empty, or larger than 100 MiB. */
    gifmaker_core_gif_ConversionError_InvalidInput = 2,
    /** FFmpeg is unavailable. */
    gifmaker_core_gif_ConversionError_EncoderUnavailable = 3,
    /** The video could not be decoded or encoded. */
    gifmaker_core_gif_ConversionError_EncodingFailed = 4,
    /** Conversion exceeded the two minute limit. */
    gifmaker_core_gif_ConversionError_TimedOut = 5,
    /** The output could not be written. */
    gifmaker_core_gif_ConversionError_OutputFailed = 6
} gifmaker_core_gif_ConversionError;

// Module: gif
/** Convert a server-owned local video into a looping, palette-optimized GIF. */
GIFMAKER_CORE_API uint64_t gifmaker_core_gif_convert(const uint8_t* input_ptr, size_t input_len, const uint8_t* output_ptr, size_t output_len, int32_t fps, int32_t width, gifmaker_core_error* out_err);


#ifdef __cplusplus
}
#endif

#endif // GIFMAKER_CORE_H

// END gifmaker_core.h
